package com.engineering.microservice.awsdynamodb.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@DynamoDBTable(tableName = "lgiemployee")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Employee  {

    @DynamoDBHashKey(attributeName = "employeeId")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;

    @DynamoDBAttribute
    private String employeeNo;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private BigDecimal totalGems;

    @DynamoDBAttribute
    private String reason;
}


